resolver: lts-6.13
packages:
  - munitweet
  - location:
      git: https://github.com/agrafix/Spock
      commit: 77333a2de5dea0dc8eba9432ab16864e93e5d70e
    extra-dep: true
    subdirs:
      - Spock
      - Spock-core
      - Spock-api
      - Spock-api-server
      - reroute
extra-deps:
  - Spock-digestive-0.3.0.0
